{
 "title": "Zookeeper",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "clustername",
    "label": "Cluster Name",
    "query": "label_values(zookeeper_monitor_follower,cluster_name)"
   },
   {
    "name": "hostaddress",
    "query": "label_values(zookeeper_monitor_outstanding_requests{cluster_name=~\"$clustername\"},host_address)"
   }
  ]
 },
 "panels": [
  { "title": "Leader Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Followers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_monitor_follower{cluster_name=~\"$clustername\",type=\"count\"}",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Synced Followers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_monitor_follower{cluster_name=~\"$clustername\",type=\"synced\"}",
     "legendFormat": "{{cluster_name}} "
    }
   ]
  },
  {
   "title": "Pending Followers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_monitor_follower{cluster_name=~\"$clustername\",type=\"pending\"}",
     "legendFormat": "{{cluster_name}} "
    }
   ]
  },
  { "title": "$clustername Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "clustername" },
  {
   "title": "Minimum Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_monitor_latency{cluster_name=~\"$clustername\",latency_type=\"zk_min_latency\"}",
     "legendFormat": "{{host_address}} "
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_monitor_latency{cluster_name=~\"$clustername\",latency_type=\"zk_avg_latency\"}",
     "legendFormat": "{{host_address}}"
    }
   ]
  },
  {
   "title": "Maximum Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_monitor_latency{cluster_name=~\"$clustername\",latency_type=\"zk_max_latency\"}",
     "legendFormat": "{{host_address}}"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_monitor_outstanding_requests{cluster_name=~\"$clustername\"}",
     "legendFormat": "{{host_address}}"
    }
   ]
  },
  {
   "title": "Packet Send/Received Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zookeeper_monitor_packets{cluster_name=~\"$clustername\", direction=\"received\"}[1m])",
     "legendFormat": "{{host_address}} - received"
    },
    {
     "expr": "rate(zookeeper_monitor_packets{cluster_name=~\"$clustername\", direction=\"sent\"}[1m]) * -1",
     "legendFormat": "{{host_address}} - send "
    }
   ]
  }
 ]
}